# Generated by Django 4.0.2 on 2022-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('familya', models.CharField(max_length=200)),
                ('telefon_nomer', models.CharField(max_length=200)),
                ('kurs', models.CharField(max_length=200)),
                ('vaqt', models.CharField(max_length=200)),
                ('registratsiya_vaqti', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
